#cloud-config
chpasswd: {expire: false}
hostname: {{ opts.parms.hostname }}
#manage_etc_hosts: localhost
manage_etc_hosts: false
password: {{ opts.parms.password }}
ssh_authorized_keys: [{{{ opts.parms.sshpubkeys }}}]
ssh_pwauth: true
timezone: Europe/London

users:
  - default
  - name: bev
    groups: sudo
    password: '$6$rounds=4096$ux8WWas3IK1b$5lKXiePn.LZeFsjvH/Q2VeVSnH6EZTaZL6t9T32BRrbIb5JenC7AAdN.yeHbmjTjTQfdTIAFcuImsfCUcpLX41'

packages:
  - qemu-guest-agent
  - nfs-client
  - bridge-utils

runcmd: # First boot
  - echo "+++++++++++++++++++++++++++++++++++ RUNCMD"

  #- apt-get update
  #- apt-get install -y nfs-client bridge-utils

  # config bridge br0 on {{ opts.parms.guest_nic }}
  - /sbin/ifdown {{ opts.parms.guest_nic }}
  #- sed -i 's/iface {{ opts.parms.guest_nic }} inet static/iface {{ opts.parms.guest_nic }} inet manual\n\nauto br0\niface br0 inet static/' /etc/network/interfaces
  - |
    cat > /etc/network/interfaces << EOF
    auto lo
    iface lo inet loopback

    iface {{ opts.parms.guest_nic }} inet manual

    auto br0
    iface br0 inet static
      address {{ opts.parms.ipaddr }}
      netmask {{ opts.parms.netmask }}
      gateway {{ opts.parms.gateway }}
      dns-nameservers {{ opts.parms.dns_nameservers }}
      bridge_ports {{ opts.parms.guest_nic }}
      up (sleep 10; ip link add veth0 type veth peer name veth1 && \\
        brctl addif br0 veth0 && \\
        ip link set dev veth0 up && \\
        ip link set dev veth1 up && \\
        echo 1 > /proc/sys/net/ipv4/ip_forward)
    EOF
  - cat /etc/network/interfaces
  - /sbin/ifup br0

  # protect interfaces from overwrite on subsequent reboots
  #- chattr +i /etc/network/interfaces

  # mount partout agent
  - mkdir -p /opt/partout/agent
  - echo "192.168.0.64:/home/bev/Documents/Brackets/partout/agent  /opt/partout/agent nfs defaults,_netdev,ro,nolock,intr,bg 0 0" >> /etc/fstab
  - mount -a
  #- mount 192.168.0.64:/home/bev/Documents/Brackets/partout/agent

  # install nodejs
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - apt-get install -y nodejs

  # run once partout agent to build openstack
  - cd /opt/partout/agent && bin/partout-agent -y --once

bootcmd:  # Every boot
  - echo "******************************************************* BOOTCMD"
  - |
    bash -x -c "
    which brctl && (
    service networking restart
    /sbin/ifdown {{ opts.parms.guest_nic }}
    cat > /etc/network/interfaces << EOF
    auto lo
    iface lo inet loopback

    iface {{ opts.parms.guest_nic }} inet manual

    auto br0
    iface br0 inet static
      address {{ opts.parms.ipaddr }}
      netmask {{ opts.parms.netmask }}
      gateway {{ opts.parms.gateway }}
      dns-nameservers {{ opts.parms.dns_nameservers }}
      bridge_ports {{ opts.parms.guest_nic }}
      up ip link add veth0 type veth peer name veth1 && \\
        brctl addif br0 veth0 && \\
        ip link set dev veth0 up && \\
        ip link set dev veth1 up && \\
        echo 1 > /proc/sys/net/ipv4/ip_forward
    EOF
    cat /etc/network/interfaces
    /sbin/ifup br0
    ) || /bin/true
    "
