#cloud-config
chpasswd: {expire: false}
hostname: {{ opts.parms.hostname }}
#manage_etc_hosts: localhost
manage_etc_hosts: false
password: {{ opts.parms.password }}
ssh_authorized_keys: [{{{ opts.parms.sshpubkeys }}}]
ssh_pwauth: true
timezone: Europe/London

packages:
  - nfs-client
  #- bridge-utils

runcmd: # First boot
  - echo "+++++++++++++++++++++++++++++++++++ RUNCMD"
  #- apt-get update
  #- apt-get install -y nfs-client bridge-utils

  # mount partout agent
  - mkdir -p /opt/partout/agent
  - echo "192.168.0.64:/home/bev/Documents/Brackets/partout/agent  /opt/partout/agent nfs defaults,_netdev,ro,nolock,intr,bg 0 0" >> /etc/fstab
  - mount -a

  # install nodejs
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - apt-get install -y nodejs

  # run once partout agent to build openstack
  - cd /opt/partout/agent && bin/partout-agent -y --once
